# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bristlecone.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bristlecone.proto',
  package='bristlecone',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x62ristlecone.proto\x12\x0b\x62ristlecone\x1a\x1cgoogle/api/annotations.proto\"\'\n\tUserParam\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x63ookie\x18\x02 \x01(\t\"^\n\x17ListInteractionsRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12$\n\x04user\x18\x03 \x01(\x0b\x32\x16.bristlecone.UserParam\"}\n\x0fInteractionItem\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x15\n\ractivity_time\x18\x02 \x01(\t\x12\x15\n\ractivity_type\x18\x03 \x01(\t\x12\x12\n\ncompletion\x18\x04 \x01(\t\x12\x0b\n\x03pid\x18\x05 \x01(\t\x12\x0b\n\x03uri\x18\x06 \x01(\t\"G\n\x18ListInteractionsResponse\x12+\n\x05items\x18\x01 \x03(\x0b\x32\x1c.bristlecone.InteractionItem\"\x07\n\x05\x45mpty2\xbf\x01\n\x12\x42ristleconeService\x12\x61\n\x10ListInteractions\x12$.bristlecone.ListInteractionsRequest\x1a%.bristlecone.ListInteractionsResponse\"\x00\x12\x46\n\x0bHealthCheck\x12\x12.bristlecone.Empty\x1a\x12.bristlecone.Empty\"\x0f\x82\xd3\xe4\x93\x02\t\x12\x07/healthb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_USERPARAM = _descriptor.Descriptor(
  name='UserParam',
  full_name='bristlecone.UserParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bristlecone.UserParam.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cookie', full_name='bristlecone.UserParam.cookie', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=103,
)


_LISTINTERACTIONSREQUEST = _descriptor.Descriptor(
  name='ListInteractionsRequest',
  full_name='bristlecone.ListInteractionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='bristlecone.ListInteractionsRequest.limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='bristlecone.ListInteractionsRequest.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='bristlecone.ListInteractionsRequest.user', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=199,
)


_INTERACTIONITEM = _descriptor.Descriptor(
  name='InteractionItem',
  full_name='bristlecone.InteractionItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='bristlecone.InteractionItem.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activity_time', full_name='bristlecone.InteractionItem.activity_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activity_type', full_name='bristlecone.InteractionItem.activity_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='completion', full_name='bristlecone.InteractionItem.completion', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='bristlecone.InteractionItem.pid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uri', full_name='bristlecone.InteractionItem.uri', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=326,
)


_LISTINTERACTIONSRESPONSE = _descriptor.Descriptor(
  name='ListInteractionsResponse',
  full_name='bristlecone.ListInteractionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='bristlecone.ListInteractionsResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=399,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='bristlecone.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=408,
)

_LISTINTERACTIONSREQUEST.fields_by_name['user'].message_type = _USERPARAM
_LISTINTERACTIONSRESPONSE.fields_by_name['items'].message_type = _INTERACTIONITEM
DESCRIPTOR.message_types_by_name['UserParam'] = _USERPARAM
DESCRIPTOR.message_types_by_name['ListInteractionsRequest'] = _LISTINTERACTIONSREQUEST
DESCRIPTOR.message_types_by_name['InteractionItem'] = _INTERACTIONITEM
DESCRIPTOR.message_types_by_name['ListInteractionsResponse'] = _LISTINTERACTIONSRESPONSE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserParam = _reflection.GeneratedProtocolMessageType('UserParam', (_message.Message,), dict(
  DESCRIPTOR = _USERPARAM,
  __module__ = 'bristlecone_pb2'
  # @@protoc_insertion_point(class_scope:bristlecone.UserParam)
  ))
_sym_db.RegisterMessage(UserParam)

ListInteractionsRequest = _reflection.GeneratedProtocolMessageType('ListInteractionsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTINTERACTIONSREQUEST,
  __module__ = 'bristlecone_pb2'
  # @@protoc_insertion_point(class_scope:bristlecone.ListInteractionsRequest)
  ))
_sym_db.RegisterMessage(ListInteractionsRequest)

InteractionItem = _reflection.GeneratedProtocolMessageType('InteractionItem', (_message.Message,), dict(
  DESCRIPTOR = _INTERACTIONITEM,
  __module__ = 'bristlecone_pb2'
  # @@protoc_insertion_point(class_scope:bristlecone.InteractionItem)
  ))
_sym_db.RegisterMessage(InteractionItem)

ListInteractionsResponse = _reflection.GeneratedProtocolMessageType('ListInteractionsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTINTERACTIONSRESPONSE,
  __module__ = 'bristlecone_pb2'
  # @@protoc_insertion_point(class_scope:bristlecone.ListInteractionsResponse)
  ))
_sym_db.RegisterMessage(ListInteractionsResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'bristlecone_pb2'
  # @@protoc_insertion_point(class_scope:bristlecone.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_BRISTLECONESERVICE = _descriptor.ServiceDescriptor(
  name='BristleconeService',
  full_name='bristlecone.BristleconeService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=411,
  serialized_end=602,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListInteractions',
    full_name='bristlecone.BristleconeService.ListInteractions',
    index=0,
    containing_service=None,
    input_type=_LISTINTERACTIONSREQUEST,
    output_type=_LISTINTERACTIONSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='bristlecone.BristleconeService.HealthCheck',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\t\022\007/health')),
  ),
])
_sym_db.RegisterServiceDescriptor(_BRISTLECONESERVICE)

DESCRIPTOR.services_by_name['BristleconeService'] = _BRISTLECONESERVICE

# @@protoc_insertion_point(module_scope)
