# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import app.services.bristlecone_pb2 as bristlecone__pb2


class BristleconeServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListInteractions = channel.unary_unary(
        '/bristlecone.BristleconeService/ListInteractions',
        request_serializer=bristlecone__pb2.ListInteractionsRequest.SerializeToString,
        response_deserializer=bristlecone__pb2.ListInteractionsResponse.FromString,
        )
    self.HealthCheck = channel.unary_unary(
        '/bristlecone.BristleconeService/HealthCheck',
        request_serializer=bristlecone__pb2.Empty.SerializeToString,
        response_deserializer=bristlecone__pb2.Empty.FromString,
        )


class BristleconeServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListInteractions(self, request, context):
    """List interaction items, each containing single-user interaction data from UAS about a single media item

    For a queried user ID and list of media item URIs, it returns a corresponding list of interaction items
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HealthCheck(self, request, context):
    """Health check

    The healthcheck endpoint is a NOOP to check services response
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BristleconeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListInteractions': grpc.unary_unary_rpc_method_handler(
          servicer.ListInteractions,
          request_deserializer=bristlecone__pb2.ListInteractionsRequest.FromString,
          response_serializer=bristlecone__pb2.ListInteractionsResponse.SerializeToString,
      ),
      'HealthCheck': grpc.unary_unary_rpc_method_handler(
          servicer.HealthCheck,
          request_deserializer=bristlecone__pb2.Empty.FromString,
          response_serializer=bristlecone__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'bristlecone.BristleconeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
