# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pseudocone.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pseudocone.proto',
  package='pseudocone',
  syntax='proto3',
  serialized_pb=_b('\n\x10pseudocone.proto\x12\npseudocone\"j\n\x17TestUserInteractionItem\x12#\n\x04user\x18\x01 \x01(\x0b\x32\x15.pseudocone.UserParam\x12*\n\x05items\x18\x02 \x03(\x0b\x32\x1b.pseudocone.InteractionItem\"}\n\x0fInteractionItem\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x15\n\ractivity_time\x18\x02 \x01(\t\x12\x15\n\ractivity_type\x18\x03 \x01(\t\x12\x12\n\ncompletion\x18\x04 \x01(\t\x12\x0b\n\x03pid\x18\x05 \x01(\t\x12\x0b\n\x03uri\x18\x06 \x01(\t\"\'\n\tUserParam\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x63ookie\x18\x02 \x01(\t\"\xb5\x01\n\x1fListTestUserInteractionsRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12$\n\x05users\x18\x03 \x03(\x0b\x32\x15.pseudocone.UserParam\x12\x0f\n\x07\x64\x61taset\x18\x04 \x01(\t\x12\x1e\n\x16start_interaction_time\x18\x05 \x01(\t\x12\x1c\n\x14test_period_duration\x18\x06 \x01(\t\"\xab\x01\n\x17ListInteractionsRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12#\n\x04user\x18\x03 \x01(\x0b\x32\x15.pseudocone.UserParam\x12\x0f\n\x07\x64\x61taset\x18\x04 \x01(\t\x12\x1c\n\x14\x65nd_interaction_time\x18\x05 \x01(\t\x12\x1d\n\x15train_period_duration\x18\x06 \x01(\t\"V\n ListTestUserInteractionsResponse\x12\x32\n\x05items\x18\x01 \x03(\x0b\x32#.pseudocone.TestUserInteractionItem\"F\n\x18ListInteractionsResponse\x12*\n\x05items\x18\x01 \x03(\x0b\x32\x1b.pseudocone.InteractionItem\"\x07\n\x05\x45mpty2\xa8\x02\n\x11PseudoconeService\x12w\n\x18ListTestUserInteractions\x12+.pseudocone.ListTestUserInteractionsRequest\x1a,.pseudocone.ListTestUserInteractionsResponse\"\x00\x12\x63\n\x14ListInteractionItems\x12#.pseudocone.ListInteractionsRequest\x1a$.pseudocone.ListInteractionsResponse\"\x00\x12\x35\n\x0bHealthCheck\x12\x11.pseudocone.Empty\x1a\x11.pseudocone.Empty\"\x00\x62\x06proto3')
)




_TESTUSERINTERACTIONITEM = _descriptor.Descriptor(
  name='TestUserInteractionItem',
  full_name='pseudocone.TestUserInteractionItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='pseudocone.TestUserInteractionItem.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='pseudocone.TestUserInteractionItem.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=138,
)


_INTERACTIONITEM = _descriptor.Descriptor(
  name='InteractionItem',
  full_name='pseudocone.InteractionItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='pseudocone.InteractionItem.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activity_time', full_name='pseudocone.InteractionItem.activity_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activity_type', full_name='pseudocone.InteractionItem.activity_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='completion', full_name='pseudocone.InteractionItem.completion', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='pseudocone.InteractionItem.pid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uri', full_name='pseudocone.InteractionItem.uri', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=265,
)


_USERPARAM = _descriptor.Descriptor(
  name='UserParam',
  full_name='pseudocone.UserParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pseudocone.UserParam.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cookie', full_name='pseudocone.UserParam.cookie', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=306,
)


_LISTTESTUSERINTERACTIONSREQUEST = _descriptor.Descriptor(
  name='ListTestUserInteractionsRequest',
  full_name='pseudocone.ListTestUserInteractionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='pseudocone.ListTestUserInteractionsRequest.limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='pseudocone.ListTestUserInteractionsRequest.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='users', full_name='pseudocone.ListTestUserInteractionsRequest.users', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='pseudocone.ListTestUserInteractionsRequest.dataset', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_interaction_time', full_name='pseudocone.ListTestUserInteractionsRequest.start_interaction_time', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_period_duration', full_name='pseudocone.ListTestUserInteractionsRequest.test_period_duration', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=490,
)


_LISTINTERACTIONSREQUEST = _descriptor.Descriptor(
  name='ListInteractionsRequest',
  full_name='pseudocone.ListInteractionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='pseudocone.ListInteractionsRequest.limit', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='pseudocone.ListInteractionsRequest.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='pseudocone.ListInteractionsRequest.user', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='pseudocone.ListInteractionsRequest.dataset', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_interaction_time', full_name='pseudocone.ListInteractionsRequest.end_interaction_time', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_period_duration', full_name='pseudocone.ListInteractionsRequest.train_period_duration', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=664,
)


_LISTTESTUSERINTERACTIONSRESPONSE = _descriptor.Descriptor(
  name='ListTestUserInteractionsResponse',
  full_name='pseudocone.ListTestUserInteractionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='pseudocone.ListTestUserInteractionsResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=666,
  serialized_end=752,
)


_LISTINTERACTIONSRESPONSE = _descriptor.Descriptor(
  name='ListInteractionsResponse',
  full_name='pseudocone.ListInteractionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='pseudocone.ListInteractionsResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=754,
  serialized_end=824,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='pseudocone.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=826,
  serialized_end=833,
)

_TESTUSERINTERACTIONITEM.fields_by_name['user'].message_type = _USERPARAM
_TESTUSERINTERACTIONITEM.fields_by_name['items'].message_type = _INTERACTIONITEM
_LISTTESTUSERINTERACTIONSREQUEST.fields_by_name['users'].message_type = _USERPARAM
_LISTINTERACTIONSREQUEST.fields_by_name['user'].message_type = _USERPARAM
_LISTTESTUSERINTERACTIONSRESPONSE.fields_by_name['items'].message_type = _TESTUSERINTERACTIONITEM
_LISTINTERACTIONSRESPONSE.fields_by_name['items'].message_type = _INTERACTIONITEM
DESCRIPTOR.message_types_by_name['TestUserInteractionItem'] = _TESTUSERINTERACTIONITEM
DESCRIPTOR.message_types_by_name['InteractionItem'] = _INTERACTIONITEM
DESCRIPTOR.message_types_by_name['UserParam'] = _USERPARAM
DESCRIPTOR.message_types_by_name['ListTestUserInteractionsRequest'] = _LISTTESTUSERINTERACTIONSREQUEST
DESCRIPTOR.message_types_by_name['ListInteractionsRequest'] = _LISTINTERACTIONSREQUEST
DESCRIPTOR.message_types_by_name['ListTestUserInteractionsResponse'] = _LISTTESTUSERINTERACTIONSRESPONSE
DESCRIPTOR.message_types_by_name['ListInteractionsResponse'] = _LISTINTERACTIONSRESPONSE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestUserInteractionItem = _reflection.GeneratedProtocolMessageType('TestUserInteractionItem', (_message.Message,), dict(
  DESCRIPTOR = _TESTUSERINTERACTIONITEM,
  __module__ = 'pseudocone_pb2'
  # @@protoc_insertion_point(class_scope:pseudocone.TestUserInteractionItem)
  ))
_sym_db.RegisterMessage(TestUserInteractionItem)

InteractionItem = _reflection.GeneratedProtocolMessageType('InteractionItem', (_message.Message,), dict(
  DESCRIPTOR = _INTERACTIONITEM,
  __module__ = 'pseudocone_pb2'
  # @@protoc_insertion_point(class_scope:pseudocone.InteractionItem)
  ))
_sym_db.RegisterMessage(InteractionItem)

UserParam = _reflection.GeneratedProtocolMessageType('UserParam', (_message.Message,), dict(
  DESCRIPTOR = _USERPARAM,
  __module__ = 'pseudocone_pb2'
  # @@protoc_insertion_point(class_scope:pseudocone.UserParam)
  ))
_sym_db.RegisterMessage(UserParam)

ListTestUserInteractionsRequest = _reflection.GeneratedProtocolMessageType('ListTestUserInteractionsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTTESTUSERINTERACTIONSREQUEST,
  __module__ = 'pseudocone_pb2'
  # @@protoc_insertion_point(class_scope:pseudocone.ListTestUserInteractionsRequest)
  ))
_sym_db.RegisterMessage(ListTestUserInteractionsRequest)

ListInteractionsRequest = _reflection.GeneratedProtocolMessageType('ListInteractionsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTINTERACTIONSREQUEST,
  __module__ = 'pseudocone_pb2'
  # @@protoc_insertion_point(class_scope:pseudocone.ListInteractionsRequest)
  ))
_sym_db.RegisterMessage(ListInteractionsRequest)

ListTestUserInteractionsResponse = _reflection.GeneratedProtocolMessageType('ListTestUserInteractionsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTTESTUSERINTERACTIONSRESPONSE,
  __module__ = 'pseudocone_pb2'
  # @@protoc_insertion_point(class_scope:pseudocone.ListTestUserInteractionsResponse)
  ))
_sym_db.RegisterMessage(ListTestUserInteractionsResponse)

ListInteractionsResponse = _reflection.GeneratedProtocolMessageType('ListInteractionsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTINTERACTIONSRESPONSE,
  __module__ = 'pseudocone_pb2'
  # @@protoc_insertion_point(class_scope:pseudocone.ListInteractionsResponse)
  ))
_sym_db.RegisterMessage(ListInteractionsResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'pseudocone_pb2'
  # @@protoc_insertion_point(class_scope:pseudocone.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_PSEUDOCONESERVICE = _descriptor.ServiceDescriptor(
  name='PseudoconeService',
  full_name='pseudocone.PseudoconeService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=836,
  serialized_end=1132,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListTestUserInteractions',
    full_name='pseudocone.PseudoconeService.ListTestUserInteractions',
    index=0,
    containing_service=None,
    input_type=_LISTTESTUSERINTERACTIONSREQUEST,
    output_type=_LISTTESTUSERINTERACTIONSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListInteractionItems',
    full_name='pseudocone.PseudoconeService.ListInteractionItems',
    index=1,
    containing_service=None,
    input_type=_LISTINTERACTIONSREQUEST,
    output_type=_LISTINTERACTIONSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='pseudocone.PseudoconeService.HealthCheck',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PSEUDOCONESERVICE)

DESCRIPTOR.services_by_name['PseudoconeService'] = _PSEUDOCONESERVICE

# @@protoc_insertion_point(module_scope)
