# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import app.pseudocone_pb2 as pseudocone__pb2


class PseudoconeServiceStub(object):
  """SERVICE

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListTestUserInteractions = channel.unary_unary(
        '/pseudocone.PseudoconeService/ListTestUserInteractions',
        request_serializer=pseudocone__pb2.ListTestUserInteractionsRequest.SerializeToString,
        response_deserializer=pseudocone__pb2.ListTestUserInteractionsResponse.FromString,
        )
    self.ListInteractionItems = channel.unary_unary(
        '/pseudocone.PseudoconeService/ListInteractionItems',
        request_serializer=pseudocone__pb2.ListInteractionsRequest.SerializeToString,
        response_deserializer=pseudocone__pb2.ListInteractionsResponse.FromString,
        )
    self.HealthCheck = channel.unary_unary(
        '/pseudocone.PseudoconeService/HealthCheck',
        request_serializer=pseudocone__pb2.Empty.SerializeToString,
        response_deserializer=pseudocone__pb2.Empty.FromString,
        )


class PseudoconeServiceServicer(object):
  """SERVICE

  """

  def ListTestUserInteractions(self, request, context):
    """List groundtruth user items, each containing a user id and a list of uris that the user has consumed
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListInteractionItems(self, request, context):
    """For a queried user ID, it returns a corresponding list of interaction items before a given date-time.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HealthCheck(self, request, context):
    """Health check
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PseudoconeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListTestUserInteractions': grpc.unary_unary_rpc_method_handler(
          servicer.ListTestUserInteractions,
          request_deserializer=pseudocone__pb2.ListTestUserInteractionsRequest.FromString,
          response_serializer=pseudocone__pb2.ListTestUserInteractionsResponse.SerializeToString,
      ),
      'ListInteractionItems': grpc.unary_unary_rpc_method_handler(
          servicer.ListInteractionItems,
          request_deserializer=pseudocone__pb2.ListInteractionsRequest.FromString,
          response_serializer=pseudocone__pb2.ListInteractionsResponse.SerializeToString,
      ),
      'HealthCheck': grpc.unary_unary_rpc_method_handler(
          servicer.HealthCheck,
          request_deserializer=pseudocone__pb2.Empty.FromString,
          response_serializer=pseudocone__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pseudocone.PseudoconeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
