import os

DEFAULT_GRPC_PORT = "50057"
DEFAULT_MAX_WORKERS = 10
DEFAULT_UAS_HOST = "https://activity.api.bbc.co.uk"
DEFAULT_LOG_LEVEL = "DEBUG"
DEFAULT_REQUEST_TIMEOUT = 5

ONE_DAY_IN_SECONDS = 60*60*24
LOG_LEVEL = os.getenv("LOG_LEVEL", DEFAULT_LOG_LEVEL)

GRPC_PORT = int(os.getenv("GRPC_PORT", DEFAULT_GRPC_PORT))
MAX_WORKERS = int(os.getenv("MAX_WORKERS", DEFAULT_MAX_WORKERS))

REQUEST_TIMEOUT = os.getenv("REQUEST_TIMEOUT", DEFAULT_REQUEST_TIMEOUT)

DATA_PATH = os.getenv("DATA_PATH")
